# Generated by Django 4.0.4 on 2022-04-30 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebookslist',
            name='pic',
            field=models.ImageField(upload_to='notebooks_pic'),
        ),
    ]
