# Generated by Django 4.0.4 on 2022-04-30 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_notebookslist_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebookslist',
            name='brand',
            field=models.CharField(choices=[('Apple', 'Apple'), ('Acer', 'Acer'), ('Asus', 'Asus'), ('Dell', 'Dell'), ('HP', 'HP'), ('Lenovo', 'Lenovo'), ('MSI', 'MSI'), ('Razer', 'Razer'), ('Samsung', 'Samsung')], default='brand', max_length=60),
        ),
    ]
