# Generated by Django 4.0.4 on 2022-05-12 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_notebookslist_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videocards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('AMD', 'AMD'), ('Gigabyte', 'Gigabyte'), ('Asus', 'Asus'), ('INNO3D', 'INNO3D'), ('MSI', 'MSI')], default='brand', max_length=60)),
                ('title', models.CharField(max_length=255)),
                ('pic', models.ImageField(upload_to='videocards_pic')),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('in_out', models.CharField(choices=[('Є в наявності', 'Є в наявності'), ('Немає в наявності', 'Немає в наявності')], max_length=255)),
            ],
        ),
    ]
