# Generated by Django 4.0.4 on 2022-05-19 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_commentsuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentsUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('date', models.DateField(auto_now=True)),
                ('name_of_stuff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.notebookslist')),
            ],
        ),
        migrations.DeleteModel(
            name='CommentsUser',
        ),
    ]
