# Generated by Django 4.0.4 on 2022-05-19 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_commentsusers_name_of_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentsusers',
            options={'verbose_name': 'CommentsUsers', 'verbose_name_plural': 'CommentsUsers'},
        ),
        migrations.CreateModel(
            name='QuestionUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_user', models.CharField(max_length=50)),
                ('comment', models.TextField()),
                ('date', models.DateField(auto_now=True)),
                ('name_of_stuff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.notebookslist')),
            ],
            options={
                'verbose_name': 'QuestionUsers',
                'verbose_name_plural': 'QuestionUsers',
            },
        ),
    ]
