# Generated by Django 4.0.4 on 2022-05-20 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_commentsusers_options_questionusers'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionUsersVideocard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_user', models.CharField(max_length=50)),
                ('comment', models.TextField()),
                ('date', models.DateField(auto_now=True)),
                ('name_of_stuff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.videocards')),
            ],
            options={
                'verbose_name': 'QuestionUsersVideocard',
                'verbose_name_plural': "QuestionUsersVideocard's",
            },
        ),
        migrations.CreateModel(
            name='CommentsUsersVideocard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_user', models.CharField(max_length=50, null=True)),
                ('comment', models.TextField()),
                ('date', models.DateField(auto_now=True)),
                ('name_of_stuff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.videocards')),
            ],
            options={
                'verbose_name': 'CommentsUsersVideocard',
                'verbose_name_plural': "CommentsUsersVideocard's",
            },
        ),
    ]
