# Generated by Django 4.0.4 on 2022-05-25 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_commentsusersvideocard_link_video_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionusersvideocard',
            name='link_video',
        ),
        migrations.AddField(
            model_name='commentsusers',
            name='link_video',
            field=models.TextField(blank=True, null=True),
        ),
    ]
