# Generated by Django 4.0.4 on 2022-05-28 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_notebookslist_pic_link_videocards_pic_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('Asus', 'Asus'), ('Acer', 'Acer'), ('BenQ', 'BenQ'), ('Dell', 'Dell'), ('LG', 'LG')], max_length=60)),
                ('title', models.CharField(max_length=255)),
                ('video_link', models.TextField(blank=True, null=True)),
                ('pic', models.ImageField(upload_to='monitors_pic')),
                ('pic_link', models.TextField(blank=True, null=True)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('in_out', models.CharField(choices=[('Є в наявності', 'Є в наявності'), ('Немає в наявності', 'Немає в наявності')], max_length=255)),
            ],
            options={
                'verbose_name': 'display',
                'verbose_name_plural': "display's",
            },
        ),
    ]
