# Generated by Django 4.0.4 on 2022-05-28 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_monitors'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Monitors',
            new_name='Monitors_list',
        ),
    ]
