# Generated by Django 4.0.4 on 2022-05-30 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_commentsusers_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentsusers',
            name='rating',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='0', max_length=15),
        ),
    ]
