# Generated by Django 4.0.4 on 2022-05-31 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_commentsusermonitor_rating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memory_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('Asus', 'Asus'), ('Acer', 'Acer'), ('BenQ', 'BenQ'), ('Dell', 'Dell'), ('LG', 'LG')], max_length=60)),
                ('title', models.CharField(max_length=255)),
                ('video_link', models.TextField(blank=True, null=True)),
                ('pic', models.ImageField(upload_to='monitors_pic')),
                ('pic_link', models.TextField(blank=True, null=True)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('in_out', models.CharField(choices=[('Є в наявності', 'Є в наявності'), ('Немає в наявності', 'Немає в наявності')], max_length=255)),
            ],
            options={
                'verbose_name': 'Memory_list',
                'verbose_name_plural': 'Memory_list',
            },
        ),
        migrations.CreateModel(
            name='QuestionUsersMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_user', models.CharField(max_length=50)),
                ('comment', models.TextField()),
                ('date', models.DateField(auto_now=True)),
                ('name_of_stuff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.monitors_list')),
            ],
            options={
                'verbose_name': 'QuestionUsersMemory',
                'verbose_name_plural': 'QuestionUsersMemory',
            },
        ),
        migrations.CreateModel(
            name='CommentsUserMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=15, null=True)),
                ('name_of_user', models.CharField(max_length=50)),
                ('comment', models.TextField()),
                ('link_video', models.TextField(blank=True, null=True)),
                ('date', models.DateField(auto_now=True)),
                ('name_of_stuff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.monitors_list')),
            ],
            options={
                'verbose_name': 'CommentsUserMemory',
                'verbose_name_plural': 'CommentsUserMemory',
            },
        ),
    ]
