# Generated by Django 4.0.4 on 2022-05-31 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_memory_list_questionusersmemory_commentsusermemory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory_list',
            name='brand',
            field=models.CharField(choices=[('AMD', 'AMD'), ('Crucial', 'Crucial'), ('HyperX', 'HyperX'), ('Kingston', 'Kingston'), ('Samsung', 'Samsung')], max_length=60),
        ),
    ]
