# Generated by Django 4.0.4 on 2022-06-22 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_commentsusermemory_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentsusermemory',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
    ]
