# Generated by Django 4.0.4 on 2022-10-02 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_commentsusers_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='HardDiskList',
            fields=[
                ('memory_list_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.memory_list')),
            ],
            options={
                'verbose_name': 'HardDiskList',
                'verbose_name_plural': 'HardDiskList',
            },
            bases=('main.memory_list',),
        ),
    ]
