# Generated by Django 4.0.4 on 2022-10-02 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_harddisklist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='harddisklist',
            options={'verbose_name': 'HardDiskList', 'verbose_name_plural': 'HardDiskLists'},
        ),
    ]
