# Generated by Django 4.0.4 on 2022-10-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_alter_harddisklist_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='HardDiskLists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('Hitachi', 'Hitachi'), ('Samsung', 'Samsung'), ('Seagate', 'Seagate'), ('Toshiba', 'Toshiba'), ('WD', 'WD')], max_length=60)),
                ('title', models.CharField(max_length=255)),
                ('video_link', models.TextField(blank=True, null=True)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='hard_disc_pic')),
                ('pic_link', models.TextField(blank=True, null=True)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('in_out', models.CharField(choices=[('Є в наявності', 'Є в наявності'), ('Немає в наявності', 'Немає в наявності')], max_length=255)),
            ],
            options={
                'verbose_name': 'HardDiskList',
                'verbose_name_plural': 'HardDiskList',
            },
        ),
    ]
