# Generated by Django 4.0.4 on 2022-10-04 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_harddisklists_buffer_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harddisklists',
            name='buffer_size',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='harddisklists',
            name='count_of_twist',
            field=models.CharField(blank=True, default=0, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='harddisklists',
            name='size',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
