# Generated by Django 4.0.4 on 2022-10-05 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_alter_harddisklists_buffer_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebookslist',
            name='display_width',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='notebookslist',
            name='processor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='notebookslist',
            name='ram',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='notebookslist',
            name='video_card',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='notebookslist',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='notebooks_pic'),
        ),
    ]
