# Generated by Django 4.0.4 on 2022-10-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_notebookslist_display_width_notebookslist_processor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebookslist',
            name='pic_link_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notebookslist',
            name='pic_link_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notebookslist',
            name='pic_link_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notebookslist',
            name='pic_link_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notebookslist',
            name='pic_link_6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notebookslist',
            name='pic_link_7',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notebookslist',
            name='pic_link_8',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notebookslist',
            name='pic_link_9',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notebookslist',
            name='video_card',
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
    ]
