# Generated by Django 4.0.4 on 2022-10-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_notebookslist_pic_link_2_notebookslist_pic_link_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='harddisklists',
            name='pic_link_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='harddisklists',
            name='pic_link_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='harddisklists',
            name='pic_link_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='harddisklists',
            name='pic_link_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='harddisklists',
            name='pic_link_6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='harddisklists',
            name='pic_link_7',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='harddisklists',
            name='pic_link_8',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='harddisklists',
            name='pic_link_9',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memory_list',
            name='pic_link_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memory_list',
            name='pic_link_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memory_list',
            name='pic_link_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memory_list',
            name='pic_link_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memory_list',
            name='pic_link_6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memory_list',
            name='pic_link_7',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memory_list',
            name='pic_link_8',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memory_list',
            name='pic_link_9',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monitors_list',
            name='pic_link_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monitors_list',
            name='pic_link_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monitors_list',
            name='pic_link_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monitors_list',
            name='pic_link_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monitors_list',
            name='pic_link_6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monitors_list',
            name='pic_link_7',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monitors_list',
            name='pic_link_8',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monitors_list',
            name='pic_link_9',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videocards',
            name='pic_link_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videocards',
            name='pic_link_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videocards',
            name='pic_link_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videocards',
            name='pic_link_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videocards',
            name='pic_link_6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videocards',
            name='pic_link_7',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videocards',
            name='pic_link_8',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videocards',
            name='pic_link_9',
            field=models.TextField(blank=True, null=True),
        ),
    ]
