# Generated by Django 4.0.4 on 2022-10-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_harddisklists_pic_link_2_harddisklists_pic_link_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocards',
            name='name_of_model',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='videocards',
            name='processor',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='videocards',
            name='vram',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
