# Generated by Django 4.0.4 on 2022-10-25 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0040_videocards_name_of_model_videocards_processor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('sur_name', models.CharField(max_length=60)),
                ('mobile_number', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=60)),
                ('state', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('num_of_post', models.CharField(max_length=10)),
                ('product_title', models.CharField(max_length=255)),
                ('product_pic', models.TextField()),
                ('product_price', models.IntegerField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OrderList',
                'verbose_name_plural': 'OrderList',
            },
        ),
    ]
