# Generated by Django 4.0.4 on 2022-10-25 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_orderlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='order_num',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
