# Generated by Django 4.0.4 on 2022-10-26 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_documentofsold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentofsold',
            name='username',
            field=models.CharField(max_length=60),
        ),
    ]
